# Generated by Django 5.1.1 on 2024-10-23 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleid', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=20)),
                ('cc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleid', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=20)),
                ('cc', models.IntegerField()),
                ('complaint', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleid', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=20)),
                ('cc', models.IntegerField()),
                ('complaint', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
