# Generated by Django 5.1.1 on 2024-10-23 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('shipfrom', models.CharField(max_length=255)),
                ('shipto', models.CharField(max_length=255)),
                ('pickdate', models.DateField()),
                ('deliverydate', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('profilepic', models.ImageField(default=None, upload_to='images')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
