# Generated by Django 5.1.1 on 2024-10-23 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mechanic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedservice',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='approved_service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechdetails',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mech_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechstatus',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mech_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mech_service', to=settings.AUTH_USER_MODEL),
        ),
    ]
