# Generated by Django 5.1.1 on 2024-10-23 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverentry',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver_entry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverstatus',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
